//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HippoCampus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class ftre_stdnt
    {
        [DisplayName("BearPass Number")]
        public int bearpass_Id { get; set; }
        [DisplayName("First Name")]
        public string ftre_stdnt_first_name { get; set; }
        [DisplayName("Last Name")]
        public string ftre_stdnt_last_name { get; set; }
        [DisplayName("Email")]
        public string ftre_stdnt_email { get; set; }
        [DisplayName("Date of Birth")]
        public System.DateTime ftre_stdnt_dob { get; set; }
        [DisplayName("Gender")]
        public string ftre_stdnt_gender { get; set; }
        [DisplayName("Arrival Date/Time")]
        public System.DateTime ftre_stdnt_arr_date_time { get; set; }
        [DisplayName("Flight Number")]
        public string ftre_stdnt_flight_num { get; set; }
        [DisplayName("Transportation Request")]
        public string ftre_stdnt_trans_req { get; set; }
        [DisplayName("Destination Description")]
        public string ftre_stdnt_des_desc { get; set; }
        [DisplayName("Other Information")]
        public string ftre_stdnt_other_desc { get; set; }
    }
}
