//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HippoCampus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HippoCampusDBEntities : DbContext
    {
        public HippoCampusDBEntities()
            : base("name=HippoCampusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ftre_stdnt> ftre_stdnt { get; set; }
        public virtual DbSet<intr_stdnt> intr_stdnt { get; set; }
    }
}
