//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HippoCampus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class wrkr_stdnt
    {
        [DisplayName("BearPass Number")]
        public int wrkr_stdnt_id { get; set; }
        [DisplayName("First Name")]
        public string wrkr_stdnt_first_name { get; set; }
        [DisplayName("Last Name")]
        public string wrkr_stdnt_last_name { get; set; }
        [DisplayName("Phone Number")]
        public string wrkr_stdnt_phone { get; set; }
        [DisplayName("Email")]
        public string wrkr_stdnt_email { get; set; }
        [DisplayName("Drive")]
        public string wrkr_stdnt_transport { get; set; }
        [DisplayName("Availability")]
        public string wrkr_stdnt_availability { get; set; }

        public bool IsDrive()
        {
            bool flag;

            if(wrkr_stdnt_transport=="Yes")
            {
                flag = true;
            }
            else
            {
                flag = false;
            }

            return flag;
        }

        public bool IsAvailable()
        {
            bool flag;
            if (wrkr_stdnt_availability == "Yes")
            {
                flag = true;
            }
            else
            {
                flag = false;
            }

            return flag;
        }
    }

    
}
